# Generated by Django 3.2.16 on 2023-05-02 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_class_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='가입일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.school'),
        ),
    ]
