# Generated by Django 3.2.16 on 2023-04-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('board', '0002_auto_20230404_2048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='My_board',
            new_name='MyBoard',
        ),
    ]
